site_name: Spatial Api
pages:
  - Home: index.md
  - Guides:
    - Getting Started: guides/getting_started.md
  - Reference:
    - Javascript Library: references/javascript_library.md
    - Rest API: references/rest_api.md
theme: readthedocs
