site_name: Spatial Api
pages:
  - Home: index.md
  - Reference:
    - Javascript Library: references/javascript_library.md
    - Rest API: references/rest_api.md
  - Guides:
    - Online Maps: guides/maps.md
theme: readthedocs
